version: "3.8"
services:
  py-gs-dev:
    build: ./
    tty: true
    working_dir: /app/py-gs/
    container_name: py-gs-dev
    volumes:
      - ..:/app/py-gs:delegated
      - ~/.ssh:/root/.ssh:delegated
